#!/bin/bash
# 007_EnvironmentAndLogging.sh - Test TCustomApplication environment and logging methods
# Auto-generated for ktests framework

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KTESTS_LIB_DIR="$SCRIPT_DIR/../../../ktests"
source "$KTESTS_LIB_DIR/ktest.sh"

# Source tcustomapplication module
TCUSTOMAPPLICATION_DIR="$SCRIPT_DIR/.."
source "$TCUSTOMAPPLICATION_DIR/tcustomapplication.sh"

# Extract test name from filename
TEST_NAME="$(basename "$0" .sh)"
kt_test_init "$TEST_NAME" "$SCRIPT_DIR" "$@"


kt_test_section "007: TCustomApplication Environment and Logging"

# Test: GetEnvironmentList with names and values
kt_test_start "GetEnvironmentList with names and values"
TCustomApplication.new myapp
declare -a env_list
myapp.GetEnvironmentList env_list "false"
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "GetEnvironmentList with names and values works"
else
    kt_test_fail "GetEnvironmentList with names and values failed"
fi
myapp.delete

# Test: GetEnvironmentList names only
kt_test_start "GetEnvironmentList names only"
TCustomApplication.new myapp
declare -a env_names
myapp.GetEnvironmentList env_names "true"
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "GetEnvironmentList names only works"
else
    kt_test_fail "GetEnvironmentList names only failed"
fi
myapp.delete

# Test: GetEnvironmentList default (names and values)
kt_test_start "GetEnvironmentList default"
TCustomApplication.new myapp
declare -a env_default
myapp.GetEnvironmentList env_default
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "GetEnvironmentList default works"
else
    kt_test_fail "GetEnvironmentList default failed"
fi
myapp.delete

# Test: EnvironmentVariable property access
kt_test_start "EnvironmentVariable property access"
TCustomApplication.new myapp
path_value=$(myapp.EnvironmentVariable "PATH")
if [[ -n "$path_value" ]]; then
    kt_test_pass "EnvironmentVariable property returns PATH value"
else
    kt_test_fail "EnvironmentVariable property failed for PATH"
fi
myapp.delete

# Test: EnvironmentVariable with non-existent variable
kt_test_start "EnvironmentVariable with non-existent variable"
TCustomApplication.new myapp
non_existent=$(myapp.EnvironmentVariable "NON_EXISTENT_VAR_12345")
if [[ -z "$non_existent" ]]; then
    kt_test_pass "EnvironmentVariable returns empty for non-existent variable"
else
    kt_test_fail "EnvironmentVariable unexpected result for non-existent: $non_existent"
fi
myapp.delete

# Test: Log with EventType and message
kt_test_start "Log with EventType and message"
TCustomApplication.new myapp
myapp.Log "etInfo" "Test log message"
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "Log with EventType and message works"
else
    kt_test_fail "Log with EventType and message failed"
fi
myapp.delete

# Test: Log with EventType, format and args
kt_test_start "Log with EventType, format and args"
TCustomApplication.new myapp
myapp.Log "etWarning" "Test %s message with %d args" "formatted" 2
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "Log with format and args works"
else
    kt_test_fail "Log with format and args failed"
fi
myapp.delete

# Test: Log with different event types
kt_test_start "Log with different event types"
TCustomApplication.new myapp
myapp.Log "etError" "Error message"
myapp.Log "etWarning" "Warning message"
myapp.Log "etInfo" "Info message"
myapp.Log "etDebug" "Debug message"
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "Log with different event types works"
else
    kt_test_fail "Log with different event types failed"
fi
myapp.delete

# Test: Log with empty message
kt_test_start "Log with empty message"
TCustomApplication.new myapp
myapp.Log "etInfo" ""
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "Log with empty message works"
else
    kt_test_fail "Log with empty message failed"
fi
myapp.delete

# Test: Log with long message
kt_test_start "Log with long message"
TCustomApplication.new myapp
long_msg="This is a very long log message that contains multiple lines and various characters to test the Log method's ability to handle complex input. It includes numbers 1234567890, special chars !@#$%^&*(), and should demonstrate proper handling of lengthy log descriptions that might be generated by applications during normal operation."
myapp.Log "etInfo" "$long_msg"
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "Log with long message works"
else
    kt_test_fail "Log with long message failed"
fi
myapp.delete

# Test: Multiple Log calls
kt_test_start "Multiple Log calls"
TCustomApplication.new myapp
for i in {1..5}; do
    myapp.Log "etInfo" "Log message $i"
done
result=$?
if [[ $result -eq 0 ]]; then
    kt_test_pass "Multiple Log calls work"
else
    kt_test_fail "Multiple Log calls failed"
fi
myapp.delete

# Test: EnvironmentVariable with special characters
kt_test_start "EnvironmentVariable with special characters"
TCustomApplication.new myapp
# Set a test environment variable with special chars
export TEST_VAR="value with spaces & special chars: !@#\$%^&*()"
var_value=$(myapp.EnvironmentVariable "TEST_VAR")
if [[ "$var_value" == "value with spaces & special chars: !@#\$%^&*()" ]]; then
    kt_test_pass "EnvironmentVariable handles special characters"
else
    kt_test_fail "EnvironmentVariable special chars issue: got '$var_value'"
fi
unset TEST_VAR
myapp.delete

kt_test_log "007_EnvironmentAndLogging.sh completed"