#!/bin/bash
S="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source /c/projects/kkbot/kbool/kcl/tdirectory/tdirectory.sh
bs=$'\x5c'; printf 'bs bytes: %s\n' "$(printf %s "$bs" | od -An -c)"
p() { printf '%-44s -> [%s]\n' "$1" "$2"; }
u="${bs}${bs}srv${bs}share${bs}f.txt"
p "getPathRoot $u" "$(tpath.getPathRoot "$u")"
p "isUNCPath $u" "$(tpath.isUNCPath "$u")"
p "getDirectoryName $u" "$(tpath.getDirectoryName "$u")"
p "getFileName $u" "$(tpath.getFileName "$u")"
p "getExtension $u" "$(tpath.getExtension "$u")"
x="${bs}${bs}?${bs}C:${bs}x"; p "isExtendedPrefixed $x" "$(tpath.isExtendedPrefixed "$x")"; p "isUNCPath $x" "$(tpath.isUNCPath "$x")"
w="C:${bs}Users${bs}me${bs}f.txt"
p "getFileName $w" "$(tpath.getFileName "$w")"
p "getFileNameWithoutExtension $w" "$(tpath.getFileNameWithoutExtension "$w")"
p "getDirectoryName $w" "$(tpath.getDirectoryName "$w")"
p "getExtension $w" "$(tpath.getExtension "$w")"
d="C:${bs}dir.d${bs}file"
p "getExtension $d" "$(tpath.getExtension "$d")"
p "hasExtension $d" "$(tpath.hasExtension "$d")"
p "changeExtension $d .txt" "$(tpath.changeExtension "$d" .txt)"
p "combine a${bs} b" "$(tpath.combine "a${bs}" b)"
p "combine C:${bs} b" "$(tpath.combine "C:${bs}" b)"
p "getFileName a${bs}b/c" "$(tpath.getFileName "a${bs}b/c")"
p "matchesPattern a${bs}b 'a?b'" "$(tpath.matchesPattern "a${bs}b" 'a?b')"
echo "## why: bracket class in getFileName"; declare -f tpath.getFileName | grep -n '##' | head -2
f="a${bs}b"; echo "  \${f##*[\\/]} test:"; printf '  [%s]\n' "${f##*[\/]}" "${f##*[$bs/]}" "${f##*[$bs]}"
echo "## combine output fed to tdirectory.getFiles (cygwin glob escapes backslash)"
W="$S/w_bs"; rm -rf "$W"; mkdir -p "$W/sub"; touch "$W/sub/a.txt" "$W/sub/b.txt"
c=$(tpath.combine "$W" sub); p "combine W sub" "${c##*/g6/}"
echo "  -d combined: $([[ -d "$c" ]] && echo yes || echo no)"
echo "  getFiles(combined): [$(tdirectory.getFiles "$c" | sed "s#.*/g6/##" | tr '\n' ' ')] rc=$?"
echo "  getFiles(posix):    [$(tdirectory.getFiles "$W/sub" | sed "s#.*/g6/##" | tr '\n' ' ')]"
echo "  isEmpty(combined): $(tdirectory.isEmpty "$c")  exists(combined): $(tdirectory.exists "$c")"
echo "  tfile.exists(combine c a.txt): $(tfile_dummy=1; source /c/projects/kkbot/kbool/kcl/tfile/tfile.sh; tfile.exists "$(tpath.combine "$c" a.txt)")"
echo "  tdirectory.copy from combined:"; tdirectory.copy "$c" "$W/copy1" && ls "$W/copy1" | tr '\n' ' '; echo
echo "  tdirectory.delete combined:"; tdirectory.delete "$c"; echo "  rc=$? sub gone: $([[ ! -e "$W/sub" ]] && echo yes || echo NO)"
rm -rf "$W"
