#!/bin/bash
S="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source /c/projects/kkbot/kbool/kcl/tpath/tpath.sh
p() { printf '%-42s -> [%s]\n' "$1" "$2"; }
echo "## P1 combine"
p 'combine a b' "$(tpath.combine a b)"
p 'combine a\ b' "$(tpath.combine 'a\' b)"
p 'combine a/ b' "$(tpath.combine 'a/' b)"
p 'combine a// b' "$(tpath.combine 'a//' b)"
p 'combine C: x' "$(tpath.combine 'C:' x)"
p 'combine C:\ x' "$(tpath.combine 'C:\' x)"
p 'combine /c/x y' "$(tpath.combine '/c/x' y)"
p 'combine "" ""' "$(tpath.combine '' '')"
p 'combine a ""' "$(tpath.combine 'a' '')"
p 'combine a C:rel' "$(tpath.combine a 'C:rel')"
p 'combine a \srv\sh' "$(tpath.combine a '\srv\sh')"
p 'combine a "b c"' "$(tpath.combine a 'b c')"
p 'combine * ?' "$(tpath.combine '*' '?')"
echo "## P1b combined path usable by bash on MSYS?"
c=$(tpath.combine /c/projects/kkbot/kbool kcl); p "combine kbool kcl" "$c"; [[ -d "$c" ]] && echo "  -d works" || echo "  -d FAILS"
ls "$c/tpath/tpath.sh" >/dev/null 2>&1 && echo "  ls works" || echo "  ls FAILS"
echo "## P2 getFileName / getExtension with backslash and mixed"
p 'getFileName a\b' "$(tpath.getFileName 'a\b')"
p 'getFileName a/b\c' "$(tpath.getFileName 'a/b\c')"
p 'getFileName a\b/c' "$(tpath.getFileName 'a\b/c')"
p 'getFileName /a/b/' "$(tpath.getFileName '/a/b/')"
p 'getExtension dir.d\file' "$(tpath.getExtension 'dir.d\file')"
p 'getExtension dir.d/file' "$(tpath.getExtension 'dir.d/file')"
p 'getExtension .bashrc' "$(tpath.getExtension '.bashrc')"
p 'getExtension file.' "$(tpath.getExtension 'file.')"
p 'getExtension a.b/c.d' "$(tpath.getExtension 'a.b/c.d')"
p 'getFileNameWithoutExtension .bashrc' "$(tpath.getFileNameWithoutExtension '.bashrc')"
p 'hasExtension file.' "$(tpath.hasExtension 'file.')"
echo "## P3 getDirectoryName"
p 'getDirectoryName /file.txt' "$(tpath.getDirectoryName '/file.txt')"
p 'getDirectoryName C:\file.txt' "$(tpath.getDirectoryName 'C:\file.txt')"
p 'getDirectoryName C:/file.txt' "$(tpath.getDirectoryName 'C:/file.txt')"
p 'getDirectoryName /home/user/' "$(tpath.getDirectoryName '/home/user/')"
p 'getDirectoryName /home/user//' "$(tpath.getDirectoryName '/home/user//')"
p 'getDirectoryName C:/Users/me\f.txt' "$(tpath.getDirectoryName 'C:/Users/me\f.txt')"
p 'getDirectoryName C:\Users\me/f.txt' "$(tpath.getDirectoryName 'C:\Users\me/f.txt')"
p 'getDirectoryName /' "$(tpath.getDirectoryName '/')"
p 'getDirectoryName //srv/share/f' "$(tpath.getDirectoryName '//srv/share/f')"
p 'getDirectoryName file' "$(tpath.getDirectoryName 'file')"
echo "## P4 changeExtension"
p 'changeExtension dir.d/file .txt' "$(tpath.changeExtension 'dir.d/file' '.txt')"
p 'changeExtension dir.d/file ""' "$(tpath.changeExtension 'dir.d/file' '')"
p 'changeExtension a.b\c .x' "$(tpath.changeExtension 'a.b\c' '.x')"
p 'changeExtension file.txt .' "$(tpath.changeExtension 'file.txt' '.')"
p 'changeExtension .bashrc .sh' "$(tpath.changeExtension '.bashrc' '.sh')"
p 'changeExtension file. txt' "$(tpath.changeExtension 'file.' 'txt')"
echo "## P5 getPathRoot / rooted"
p 'getPathRoot //srv/share/f' "$(tpath.getPathRoot '//srv/share/f')"
p 'getPathRoot \srv\share\f' "$(tpath.getPathRoot '\srv\share\f')"
p 'getPathRoot C:\x' "$(tpath.getPathRoot 'C:\x')"
p 'getPathRoot C:x' "$(tpath.getPathRoot 'C:x')"
p 'isPathRooted \x' "$(tpath.isPathRooted '\x')"
p 'isUNCPath \?\C:\x' "$(tpath.isUNCPath '\?\C:\x')"
p 'isExtendedPrefixed \?\C:\x' "$(tpath.isExtendedPrefixed '\?\C:\x')"
p 'driveExists Q:' "$(tpath.driveExists 'Q:')"
echo "## P6 getFullPath"
cd "$S"
p 'getFullPath nonexistent.txt' "$(tpath.getFullPath 'nonexistent.txt')"
p 'getFullPath ./nope/../x' "$(tpath.getFullPath './nope/../x')"
p 'getFullPath C:\Windows' "$(tpath.getFullPath 'C:\Windows')"
p 'getFullPath -e' "$(tpath.getFullPath '-e')"
p 'getFullPath probe_tpath.sh' "$(tpath.getFullPath 'probe_tpath.sh')"
echo "## P7 valid chars"
p 'hasValidFileNameChars a:b' "$(tpath.hasValidFileNameChars 'a:b')"
p 'hasValidFileNameChars a<b>c|d"' "$(tpath.hasValidFileNameChars 'a<b>c|d"')"
p 'hasValidFileNameChars a\b' "$(tpath.hasValidFileNameChars 'a\b')"
p 'hasValidPathChars /x/a*b true' "$(tpath.hasValidPathChars '/x/a*b' true)"
p 'hasValidPathChars C:\x<y' "$(tpath.hasValidPathChars 'C:\x<y')"
p 'isValidFileNameChar ~' "$(tpath.isValidFileNameChar '~')"
p 'isValidFileNameChar \' "$(tpath.isValidFileNameChar '\')"
p 'isValidFileNameChar :' "$(tpath.isValidFileNameChar ':')"
echo "## P8 matchesPattern nocasematch leak"
shopt -s nocasematch; tpath.matchesPattern a b false >/dev/null; shopt -q nocasematch && echo "nocasematch preserved" || echo "nocasematch CLEARED by matchesPattern"
shopt -u nocasematch
p 'matchesPattern "a b" "a?b"' "$(tpath.matchesPattern 'a b' 'a?b')"
p 'matchesPattern x/y "*"' "$(tpath.matchesPattern 'x/y' '*')"
echo "## P9 getAttributes -L inversion"
W="$S/w_tpath"; rm -rf "$W"; mkdir -p "$W"; cd "$W"; echo x > f.txt
declare -f tpath.getAttributes | grep -n 'stat_flags="-L"' | head -1
p 'getAttributes f.txt' "$(tpath.getAttributes f.txt)"
chmod 444 f.txt; p 'getAttributes f.txt (444)' "$(tpath.getAttributes f.txt)"
echo "## P10 temp path / random names"
p 'getTempPath' "$(tpath.getTempPath)"
p 'getRandomFileName x2' "$(tpath.getRandomFileName) $(tpath.getRandomFileName)"
p 'getGUIDFileName' "$(tpath.getGUIDFileName)"
p 'getGUIDFileName true' "$(tpath.getGUIDFileName true)"
echo "## P11 fork counts (uname/realpath per call)"
declare -f tpath.driveExists tpath.getDocumentsPath tpath.getDownloadsPath | grep -c 'uname -s'
cd "$S"; rm -rf "$W"
