source /c/projects/kkbot/kbool/kcl/dateutils/dateutils.sh
echo "bash $BASH_VERSION"
echo "--- leading-zero (octal) inputs"
echo -n "encodeDate 2011 08 09 -> "; dateutils.encodeDate 2011 08 09; echo " rc=$?"
echo -n "encodeDate 2011 07 09 -> "; dateutils.encodeDate 2011 07 09; echo " rc=$?"
echo -n "encodeTime 09 05 08 000 -> "; dateutils.encodeTime 09 05 08 000; echo " rc=$?"
echo -n "isValidDate 2011 08 15 -> "; dateutils.isValidDate 2011 08 15; echo " rc=$?"
echo -n "daysInAMonth 2011 09 -> "; dateutils.daysInAMonth 2011 09; echo " rc=$?"
echo -n "incMonth 0 08 -> "; dateutils.incMonth 0 08; echo " rc=$?"
echo -n "recodeMonth 0 09 -> "; dateutils.recodeMonth 0 09; echo " rc=$?"
echo -n "encodeDateWeek 2011 09 1 -> "; dateutils.encodeDateWeek 2011 09 1; echo " rc=$?"
echo -n "startOfAMonth 2011 08 -> "; dateutils.startOfAMonth 2011 08; echo " rc=$?"
echo "--- via read from a zero-padded string (typical caller pattern)"
IFS=- read -r y m d <<< "2011-08-09"; echo -n "encodeDate $y $m $d -> "; dateutils.encodeDate "$y" "$m" "$d"; echo " rc=$?"
echo "--- empty / non-numeric args"
echo -n "dayOf '' -> "; dateutils.dayOf ""; echo " rc=$?"
echo -n "decodeDateTime '' -> "; dateutils.decodeDateTime ""; echo " rc=$?"
echo -n "daysBetween '' '' -> "; dateutils.daysBetween "" ""; echo " rc=$?"
echo -n "incDay abc -> "; dateutils.incDay abc; echo " rc=$?"
echo "--- arithmetic injection through unvalidated args"
echo -n "incDay 'x[\$(echo INJECTED>&2)]' -> "; dateutils.incDay 'x[$(echo INJECTED>&2)]'; echo " rc=$?"
echo -n "isValidDate 'x[\$(echo INJECTED2>&2)]' 1 1 -> "; dateutils.isValidDate 'x[$(echo INJECTED2>&2)]' 1 1; echo " rc=$?"
echo -n "tryISOStrToDate via _valid_date is safe? tryISOStrToDate 'x[\$(echo INJ3>&2)]' -> "; dateutils.tryISOStrToDate 'x[$(echo INJ3>&2)]'; echo " rc=$?"
echo -n "compareDateTime 'a[\$(echo INJ4>&2)]' 0 -> "; dateutils.compareDateTime 'a[$(echo INJ4>&2)]' 0; echo " rc=$?"
