source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh
echo "bash $BASH_VERSION"
echo "--- ambient nocasematch + case-sensitive pattern: prefix-strip"
shopt -s nocasematch
TRegEx.match "xabcABC" "ABC"; echo "match idx=$RESULT_INDEX (expected 4) m=$RESULT"
r=$(TRegEx.replace "xabcABC" "ABC" "_"); echo "replace -> [$r] (expected xabc_)"
TRegEx.replace "xabcABC" "ABC" "_" >/dev/null; echo "replace RESULT -> [$RESULT]"
parts=(); TRegEx.split "xabcABC" "ABC" parts; echo "split -> ${#parts[@]}: $(printf '[%s]' "${parts[@]}") (expected [xabc][])"
o=(); f=(); TRegEx.matches "xabcABC" "ABC" o f; echo "matches -> n=$RESULT offs=${f[*]} (expected 1 / 4)"
shopt -u nocasematch
echo "--- same without ambient nocasematch"
TRegEx.match "xabcABC" "ABC"; echo "match idx=$RESULT_INDEX"
r=$(TRegEx.replace "xabcABC" "ABC" "_"); echo "replace -> [$r]"
echo "--- i flag: match ABC first occurrence"
TRegEx.match "xabcABC" "abc" i; echo "i: m=$RESULT idx=$RESULT_INDEX (expected abc/1)"
TRegEx.match "xABCabc" "abc" i; echo "i: m=$RESULT idx=$RESULT_INDEX (expected ABC/1)"
r=$(TRegEx.replace "xABCabc" "abc" "_" - i); echo "i replace -> [$r] (expected x__)"
echo "--- nocasematch restore"
shopt -s nocasematch; TRegEx.isMatch a A i; shopt -q nocasematch && echo "restored on" || echo "LEAK off"
shopt -u nocasematch; TRegEx.isMatch a A i; shopt -q nocasematch && echo "LEAK on" || echo "restored off"
echo "--- flags parsing"
TRegEx.isMatch "ABC" "abc" Multiline && echo "flags=Multiline => case-insensitive (i in word)" || echo "Multiline: no"
TRegEx.isMatch "ABC" "abc" m && echo "m flag => insensitive?!" || echo "m: sensitive ok"
echo "--- set -e"
bash -c 'set -e; source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; a=(); TRegEx.matches "a1b2" "[0-9]" a; echo "matches n=$RESULT ${a[*]}"' 2>&1; echo "rc=$?"
bash -c 'set -e; source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; r=$(TRegEx.replace "a1b2" "[0-9]" "\$0\$0"); echo "replace [$r]"' 2>&1; echo "rc=$?"
bash -c 'set -e; source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; TRegEx.match "abc" "x" || true; echo "match nomatch survived"; TRegEx.match "abc" "b"; echo "match ok survived $RESULT"' 2>&1; echo "rc=$?"
bash -c 'set -e; source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; x=$(TRegEx.escape "a.b"); echo "escape [$x]"' 2>&1; echo "rc=$?"
echo "--- split limit injection"
p=(); TRegEx.split "a,b,c" "," p 'x[$(echo INJECTED >&2)]'; echo "split n=$RESULT"
r=$(TRegEx.replace "a,b" "," ";" 'x[$(echo INJECTED2 >&2)]' 2>&1); echo "replace -> [$r]"
echo "--- nameref names"
TRegEx.matches "abc" "b" "1bad" 2>&1; echo "bad name rc=$?"
TRegEx.matches "abc" "b" "RESULT" 2>&1; echo "name RESULT rc=$? RESULT=[$RESULT]"
TRegEx.matches "abc" "b" "__tre_g" 2>&1; echo "name __tre_g rc=$?"
echo "--- escape roundtrip all metas + special"
for c in '\' '.' '^' '$' '*' '+' '?' '(' ')' '[' ']' '{' '}' '|' '-' '/' ' ' $'\n' '#' '~' '&' 'é'; do
  e=$(TRegEx.escape "a${c}b"); TRegEx.match "xa${c}by" "$e"; rc=$?; [[ $rc == 0 && "$RESULT" == "a${c}b" ]] || echo "escape FAIL for [$c]: esc=[$e] rc=$rc RESULT=[$RESULT]"
done; echo "escape loop done"
echo "--- multibyte index"
TRegEx.match "héllo wörld" "w.rld"; echo "LANG=$LANG LC_ALL=$LC_ALL idx=$RESULT_INDEX len=$RESULT_LENGTH m=$RESULT"
LC_ALL=C.UTF-8 bash -c 'source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; TRegEx.match "héllo wörld" "w.rld"; echo "C.UTF-8 idx=$RESULT_INDEX len=$RESULT_LENGTH m=$RESULT"'
LC_ALL=C bash -c 'source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; TRegEx.match "héllo wörld" "w.rld"; echo "C idx=$RESULT_INDEX len=$RESULT_LENGTH m=[$RESULT] rc=$?"'
