source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh
echo "--- raw locale check: LANG=[$LANG] LC_ALL=[$LC_ALL] LC_CTYPE=[$LC_CTYPE]"
[[ "wörld" =~ w.rld ]] && echo "raw . matches ö (char)" || echo "raw . does NOT match ö (byte mode)"
[[ "wörld" =~ w..rld ]] && echo "raw .. matches ö => byte mode confirmed"
echo "len(ö)=${#ö} len(wörld)=$(s=wörld; echo ${#s})"
echo "--- set -e direct forms"
bash -c 'set -e; source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; TRegEx.match "abc" "x"; echo "match nomatch direct survived idx=$RESULT_INDEX"' 2>&1; echo "rc=$?"
bash -c 'set -e; source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; TRegEx.replace "a1b2" "[0-9]" "#"; echo "replace direct survived"' 2>&1; echo "rc=$?"
bash -c 'set -e; source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; p=(); TRegEx.split "a,b" "," p; echo "split direct survived ${p[*]}"' 2>&1; echo "rc=$?"
bash -c 'set -e; source /c/projects/kkbot/kbool/kcl/tregex/tregex.sh; TRegEx.escape "a.b" >/dev/null; echo "escape direct survived $RESULT"' 2>&1; echo "rc=$?"
echo "--- zero-length & anchors in scans"
a=(); TRegEx.matches "" "a*" a; echo "matches '' a* -> n=$RESULT"
a=(); o=(); TRegEx.matches "abc" '$' a o; echo "matches abc \$ -> n=$RESULT offs=${o[*]} (.NET: 1 @3)"
a=(); o=(); TRegEx.matches "ab cd" '\b' a o; echo "matches 'ab cd' \b -> n=$RESULT offs=${o[*]} (.NET: 4 @0,2,3,5)"
r=$(TRegEx.replace "abc" '$' "!"); echo "replace abc \$ ! -> [$r] (.NET abc!)"
r=$(TRegEx.replace "abc" 'x*' "-"); echo "replace abc x* -> [$r] (.NET -a-b-c-)"
p=(); TRegEx.split "ab" "x*" p; echo "split ab x* -> $(printf '[%s]' "${p[@]}")"
a=(); o=(); TRegEx.matches "aab" "b*" a o; echo "matches aab b* -> n=$RESULT $(printf '[%s]' "${a[@]}") offs=${o[*]}"
echo "--- prefix-strip with special chars in match text"
TRegEx.match 'xx\yy' '\'; echo "backslash idx=$RESULT_INDEX (2)"
TRegEx.match 'xx*yy' '\*'; echo "star idx=$RESULT_INDEX (2)"
TRegEx.match 'xx[a]yy' '\[a\]'; echo "bracket idx=$RESULT_INDEX (2)"
TRegEx.match $'l1\nl2' $'\n'; echo "newline idx=$RESULT_INDEX (2)"
TRegEx.match 'a/b/c' '/b/'; echo "slash idx=$RESULT_INDEX (1) m=$RESULT"
TRegEx.match $'ab\ncd' '^cd'; echo "multiline ^cd rc=$? (.NET multiline: match; ERE: no)"
TRegEx.match $'ab\ncd' 'b.c'; echo ". matches newline rc=$? m=[$RESULT]"
echo "--- replacement grammar"
TRegEx.match "abcdefghijk" '(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)' ; echo "groups=${#RESULT_GROUPS[@]}"
r=$(TRegEx.replace "abcdefghijk" '(a)(b)(c)(d)(e)(f)(g)(h)(i)(j)(k)' '[$10][${10}][$11][${11}][$0][$&][$$][$][$x][\1][&]'); echo "repl -> $r"
r=$(TRegEx.replace "ab" '(a)(b)' '$2$1' ); echo "swap -> $r"
r=$(TRegEx.replace "a" 'a' '$'); echo "trailing \$ -> [$r]"
r=$(TRegEx.replace "aaa" "a" "b" 2); echo "maxCount 2 -> $r (bba)"
r=$(TRegEx.replace "aaa" "a" "b" -1); echo "maxCount -1 -> $r"
echo "--- trailing newline loss via \$()"
r=$(TRegEx.replace $'a\n\n' "a" "b"); printf 'captured=%q ' "$r"; TRegEx.replace $'a\n\n' "a" "b" >/dev/null; printf 'RESULT=%q\n' "$RESULT"
echo "--- leftmost-longest / group semantics vs PCRE"
TRegEx.match "ab" "a|ab"; echo "a|ab -> $RESULT"
TRegEx.match "aaa" "(a*)(a)"; echo "(a*)(a) groups: [${RESULT_GROUPS[0]}][${RESULT_GROUPS[1]}]"
TRegEx.match "abab" "(ab)*"; echo "(ab)* group: [${RESULT_GROUPS[0]}] (PCRE: ab)"
TRegEx.match "ab" "(a)|(b)"; echo "(a)|(b) on ab: g=${#RESULT_GROUPS[@]} [${RESULT_GROUPS[0]}][${RESULT_GROUPS[1]}]"
TRegEx.match "b" "(a)|(b)"; echo "(a)|(b) on b: g=${#RESULT_GROUPS[@]} [${RESULT_GROUPS[0]}][${RESULT_GROUPS[1]}]"
echo "--- \d \w \s"
TRegEx.isMatch "5" '\d'; echo "\d on 5 rc=$?"; TRegEx.isMatch "d" '\d'; echo "\d on d rc=$?"
TRegEx.isMatch "a b" 'a\sb'; echo "\s rc=$?"
echo "--- perf"
s=$(printf 'ab,%.0s' {1..2000}); t0=$EPOCHREALTIME; TRegEx.replace "$s" "," ";" >/dev/null; t1=$EPOCHREALTIME; echo "replace 2000 matches in 6000 chars: $(awk -v a=$t0 -v b=$t1 'BEGIN{print b-a}')s"
a=(); t0=$EPOCHREALTIME; TRegEx.matches "$s" "ab" a; t1=$EPOCHREALTIME; echo "matches n=$RESULT: $(awk -v a=$t0 -v b=$t1 'BEGIN{print b-a}')s"
big=$(printf 'x%.0s' {1..50000}); t0=$EPOCHREALTIME; e=$(TRegEx.escape "$big"); t1=$EPOCHREALTIME; echo "escape 50k ascii: $(awk -v a=$t0 -v b=$t1 'BEGIN{print b-a}')s"
